import { Project } from '../types';

/**
 * Generates a standalone HTML file containing all slides and a built-in player.
 */
export const exportProjectToHTML = (project: Project): void => {
  const slideContentArray = project.slides.map(s => JSON.stringify(s.html));

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${project.title} - Flash Slides Presentation</title>
    <style>
        body, html { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; background: #000; }
        #app { width: 100%; height: 100%; position: relative; display: flex; align-items: center; justify-content: center; }
        .slide-container { 
            position: absolute; 
            top: 0; left: 0; width: 100%; height: 100%; 
            display: flex; align-items: center; justify-content: center;
            opacity: 0;
            transition: opacity 0.7s ease-in-out;
            pointer-events: none;
            z-index: 0;
        }
        .slide-container.active { opacity: 1; z-index: 10; pointer-events: auto; }
        iframe { width: 100%; height: 100%; border: none; background: transparent; }
        .controls {
            position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%);
            display: flex; gap: 10px; z-index: 100;
            opacity: 0; transition: opacity 0.3s;
        }
        body:hover .controls { opacity: 1; }
        .dot { width: 8px; height: 8px; background: rgba(255,255,255,0.3); border-radius: 50%; }
        .dot.active { background: #6366f1; width: 30px; border-radius: 4px; transition: all 0.3s; }
        .watermark {
            position: fixed; bottom: 20px; right: 20px; color: rgba(255,255,255,0.2);
            font-family: sans-serif; font-size: 12px; pointer-events: none; z-index: 100;
        }
    </style>
</head>
<body>
    <div id="app">
        <!-- Slides will be injected here -->
    </div>

    <div class="controls" id="controls"></div>
    <div class="watermark">Generated by Flash Slides</div>

    <script>
        const slideData = [${slideContentArray.join(',')}];
        let currentIndex = 0;
        const app = document.getElementById('app');
        const controls = document.getElementById('controls');

        // Initialize Slides
        slideData.forEach((html, index) => {
            const container = document.createElement('div');
            container.className = 'slide-container' + (index === 0 ? ' active' : '');
            container.id = 'slide-' + index;
            
            // Aspect Ratio wrapper similar to app
            const wrapper = document.createElement('div');
            wrapper.style.cssText = "width: 100%; height: 100%; max-width: 177.78vh; max-height: 56.25vw; aspect-ratio: 16/9; position: relative; background: #000;";
            
            const iframe = document.createElement('iframe');
            iframe.srcdoc = html;
            iframe.sandbox = "allow-scripts";
            iframe.id = 'iframe-' + index;
            
            wrapper.appendChild(iframe);
            container.appendChild(wrapper);
            app.appendChild(container);

            // Controls
            const dot = document.createElement('div');
            dot.className = 'dot' + (index === 0 ? ' active' : '');
            controls.appendChild(dot);
        });

        function updateSlide(newIndex) {
            if (newIndex < 0 || newIndex >= slideData.length) return;
            
            // Update Active Classes
            document.querySelectorAll('.slide-container').forEach(el => el.classList.remove('active'));
            document.getElementById('slide-' + newIndex).classList.add('active');

            document.querySelectorAll('.dot').forEach(el => el.classList.remove('active'));
            document.querySelectorAll('.dot')[newIndex].classList.add('active');

            // Trigger Animation Replay
            const iframe = document.getElementById('iframe-' + newIndex);
            if(iframe && iframe.contentWindow) {
                iframe.contentWindow.postMessage('play', '*');
            }

            currentIndex = newIndex;
        }

        // Keyboard Navigation
        window.addEventListener('keydown', (e) => {
            if (e.key === 'ArrowRight' || e.key === ' ' || e.key === 'Enter') {
                updateSlide(currentIndex + 1);
            } else if (e.key === 'ArrowLeft') {
                updateSlide(currentIndex - 1);
            }
        });

        // Click Zones
        const width = window.innerWidth;
        window.addEventListener('click', (e) => {
            if (e.clientX > width / 2) updateSlide(currentIndex + 1);
            else updateSlide(currentIndex - 1);
        });

    </script>
</body>
</html>
  `;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title.replace(/\s+/g, '_') || 'presentation'}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Exports the project data to a JSON file for backup/restore.
 */
export const exportProjectToJSON = (project: Project): void => {
  const jsonContent = JSON.stringify(project, null, 2);
  const blob = new Blob([jsonContent], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.title.replace(/\s+/g, '_') || 'project'}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Reads and parses a JSON file into a Project object.
 */
export const parseProjectJSON = (file: File): Promise<Project> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const json = e.target?.result as string;
        const project = JSON.parse(json);
        
        // Basic validation
        if (!project.id || !project.title || !Array.isArray(project.slides)) {
          throw new Error('Invalid project file format');
        }
        
        resolve(project);
      } catch (error) {
        reject(error);
      }
    };
    
    reader.onerror = () => reject(new Error('Failed to read file'));
    reader.readAsText(file);
  });
};